project:
  type: website
  output-dir: docs

website:
  title: "NFL Formation Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Table of Contents
      - href: abstract.qmd
        text: Abstract
      - href: intro.qmd
        text: Introduction
      - href: trends.qmd
        text: Trends in League Usage
      - href: third_down.qmd
        text: 3rd and Short Analysis
      - href: case_study.qmd
        text: Formation Switching
      - href: goalline.qmd
        text: Goal Line Efficiency
      - href: descriptive_models.qmd
        text: Modeling Formation Tendency
      - href: predictive_models.qmd
        text: Predictive Modeling
      - href: validation.qmd
        text: Model Validation
      - href: results.qmd
        text: Results & Key Findings
      - href: limitations.qmd
        text: Limitations  
      - href: app.qmd
        text: Play Recommender

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    css: styles.css
    page-layout: article
